### ISSUE TITLE
Non-interactive Mode

### ISSUE THREAD

**Issue by rcrivelli** [liferay/generator-liferay-fragments#151]
Hi

We like to deploy our Liferay Fragments on the Liferay-Servers with Atlassian Bamboo.
Is there any non-interactive mode for this generator to set the hostname, user, password?

Or is there an other way, to automate the deployment of Liferay Fragments?

BR
Raphael

**Comment by p2kmgcl** [comment]
Hi @rcrivelli,

Sure, you can pass every parameter to any command and it won't prompt for values:

```
$ yo liferay-fragments:import --help
Usage:
  yo liferay-fragments:import [<host>] [<username>] [<password>] [<groupId>] [<watch>] [options]

Options:
  -h,   --help           # Print the generator's options and usage
        --skip-cache     # Do not remember prompt answers             Default: false
        --skip-install   # Do not automatically install dependencies  Default: false
        --force-install  # Fail on install dependencies error         Default: false

Arguments:
  host        Type: String  Required: false
  username    Type: String  Required: false
  password    Type: String  Required: false
  groupId     Type: String  Required: false
  watch       Type: String  Required: false
```

So you can write `npm run import` (or `yo liferay-fragments:import`) with those arguments:

```
npm run import -- --username=myuser --pasword=mypassword [...]
```

Just one more thing: I don't remember is `groupId` needs to be specified as `--groupId` or `--group-id` so please try both if it fails :smile:

**Comment by rcrivelli** [comment]
perfect thx.
