### ISSUE TITLE
npm run import doesn't work for fragment with thumbnail

### ISSUE THREAD

**Issue by rozamirandar** [liferay/generator-liferay-fragments#153]
`version 1.7.0`

When I try to run `npm run import` for a fragment with a thumbnail I get the following error

```
1 of 1 fragment was not imported due to errors.

✔ Collection Sample Collection
  ✘ Fragment banner-rotator was not imported due to fragment errors
  ENOENT: no such file or directory, open 'thumbnail.png'
```

This is my fragment.json
```
{
  "cssPath": "styles.css",
  "configurationPath": "configuration.json",
  "htmlPath": "index.html",
  "jsPath": "main.js",
  "name": "banner-rotator",
  "thumbnailPath": "thumbnail.png",
  "type": "section"
}
```

I pushed a sample project to https://github.com/rozamirandar/sample-fragments

**Comment by sandrodw3** [comment]
Hey @rozamirandar! Thanks for catching the bug, we have filled a ticket in Jira for it, just in case you want to track it: https://issues.liferay.com/browse/LPS-117083

**Comment by victorg1991** [comment]
Hey @rozamirandar the pr that fixes the bug was merged and a new version will be released soon :)

**Comment by rozamirandar** [comment]
Cool, thanks @victorg1991
