### ISSUE TITLE
Fragment Icons

### ISSUE THREAD

**Issue by faragos** [liferay/generator-liferay-fragments#180]
is there a possibility to provide this icon in the configuration similiar to the thumbnail?
![image](https://user-images.githubusercontent.com/10152106/98350796-1b0de280-201c-11eb-8294-6a08a3edeca3.png)

**Comment by p2kmgcl** [comment]
Yep, in fragment.json you can add "icon" and use a Clay name https://clayui.com/docs/components/icon.html
