### ISSUE TITLE
Multilanguage Fragments

### ISSUE THREAD

**Issue by faragos** [liferay/generator-liferay-fragments#181]
Is there a possibility how I can serve the language keys with the fragment/collection/module itself?

And also is there a way to have different names for each language for a fragment/composition?

I think the basic componenents already have that and the ones created with blade also do that 🙂

**Comment by p2kmgcl** [comment]
Hi @faragos,
I'm so sorry for the delay. We are redirecting all issue tickets to JIRA, which is part of our daily workflow, so we can answer as soon as we can.

Currently there is now way to add translations to fragments, at least not something that we provide by default. With the new custom workflow that we've added on 1.8 maybe you can tweak webpack's configuration to generate multiple fragments (one per language), but I guess this is not ideal.

I've created a feature request for you in JIRA, please feel free to subscribe or add extra information if you want to follow the thread: https://issues.liferay.com/browse/LPS-124121
