### ISSUE TITLE
Reloading fragment preview should keep the current fragment selected

### ISSUE THREAD

**Issue by jwahdatehagh** [liferay/generator-liferay-fragments#183]
Currently when manually reloading previewed fragments, the selected fragment gets reset and you have to navigate to it again. The selection get's added to the query string but is being reset on load.

**Comment by p2kmgcl** [comment]
Hey @jwahdatehagh, I have created a JIRA ticket, will fix this there. Thanks for reporting!
https://issues.liferay.com/browse/LPS-152388
