### ISSUE TITLE
Add an example on how to make React fragments editable

### ISSUE THREAD

**Issue by jwahdatehagh** [liferay/generator-liferay-fragments#184]
The current generator doesn't illustrate how to use the `lfr-editable` syntax for JSX-rendered html.

Would be nice if the generator added a simple example to start off of like in the barebones version.

**Comment by p2kmgcl** [comment]
Hi @jwahdatehagh, the reason is that we currently don't support editables inside JSX :sweat_smile: 
We are trying to move all our related tickets to JIRA, could you open a feature request there? https://issues.liferay.com/secure/CreateIssue!default.jspa

**Comment by jwahdatehagh** [comment]
Hi @p2kmgcl - thanks, i understand... I don't have an account with the liferay jira installation, so i can't create the ticket. From my perspective this would be a very reasonable / important feature to have.

Best, jalil
