### ISSUE TITLE
Fragment assets should be preprocessed with a custom workflow

### ISSUE THREAD

**Issue by p2kmgcl** [liferay/generator-liferay-fragments#19]
Now we've got a valid workflow for developing fragments, we should start making it more customizable. We've talked about using SASS or event Babel for preprocessing fragments, but it would be even more useful that fragment creators could define customized processing while creating fragments.

```
main.js -> [Babel] -> main.js
styles.scss -> [SASS] -> styles.css
index.pug -> [Pug] -> index.html
```

```
[customCode.ts, otherCode.ts] -> [Typescript] -> main.js
styles.pcss -> [PostCSS] -> styles.css
index.html -> index.html
```

For this purpose we should:

- Define how these steps are defined.
- Provide scripts for helping with this process.
- Allow generating fragments.zip with arbitrary content.

**Comment by trevor-ryan-burkholder** [comment]
I am working on a further implementation I'm currently using Gulp to compile my SASS and TypeScript before the fragments get imported into Liferay. I'm going to be working on making this process more robust. I'll post some updates here in the future if others find this useful.

**Comment by faragos** [comment]
What's the state on this issue? It looks very promising and IMO this is one of the few things that are still missing.

**Comment by p2kmgcl** [comment]
Hey @faragos, although we are trying to keep track of missing functionality and bugs inside this repo, for the case that anyone wants to contribute to the project (:heart:  @TBurk83), we work under Jira, and we still have no plans about this issue.

However, as I said, contributions are welcome :)

**Comment by faragos** [comment]
@TBurk83 How is your implementation going? Are you still working on it? Do you maybe need some help?😃

**Comment by faragos** [comment]
I implemented the SCSS part by myself for now and created a pull request. I'm waiting for any feedback 😃

**Comment by p2kmgcl** [comment]
Released here: https://github.com/liferay/generator-liferay-fragments/releases/tag/v1.8.0
