### ISSUE TITLE
Compatibility issue while running preview command

### ISSUE THREAD

**Issue by MarketaHalikova** [liferay/generator-liferay-fragments#65]
After running the preview command there is an error while _checking site compability..._

"Your Liferay Server cannot generate fragment previews.
Update it to a more recent version to use this feature.

If this an error, please report an issue at
https://www.npmjs.com/package/generator-liferay-fragments"

The Liferay Server to which I am connecting is 7.2 DXP (also tried with CE). Is there any update/configuration necessary for the preview feature to run? Everything else (except for the watch feature runs fine)

**Comment by p2kmgcl** [comment]
Hey @MarketaHalikova, I was checking this with the team, and although we provide this functionality in the toolkit, the backend is only available in `master` branch. However, this functionality will be available soon (I am not sure if it will be included in the next fixpack o the next service pack). I am keeping this issue open, so we can update the documentation when it is available. For now, I am going to update the README.md file to tell it is only released on `master`.

Moreover, if you are going to try it anyway, you have to enable [Oauth 2](https://web.liferay.com/marketplace/-/mp/application/109571986) module to provide proper authentication (it's a free module available in the marketplace).

Thanks for trying this! :cat:

**Comment by p2kmgcl** [comment]
@MarketaHalikova I checked it and it should be available from 7.2 fixpack 1, we are going to update the documentation to reflect this :)

**Comment by p2kmgcl** [comment]
@MarketaHalikova as we already know from which version will it be available and we added it to the documentation I am closing this
