### ISSUE TITLE
Add support for writing sass

### ISSUE THREAD

**Issue by rdai10** [liferay/generator-liferay-fragments#71]
It will be a more pleasant experience for someone using `generator-liferay-fragments` to be able to write sass if they so choose. If a user is content with writing css, they can continue to do so in `styles.css`. However if a user wants to write sass, there could be an additional process that compiles `sass` to `css` and outputs it in the `styles.css`.

**Comment by p2kmgcl** [comment]
Hi @rdai10, I am closing this as duplicated of https://github.com/liferay/generator-liferay-fragments/issues/19

Thanks for suggesting!

If you want to suggest how the build process should happen and/or which tools should we use please feel free to add a comment in the linked issue :)
