### ISSUE TITLE
Automate and normalize publish process

### ISSUE THREAD

**Issue by p2kmgcl** [liferay/generator-liferay-fragments#75]
Currently we publish new versions manually. Although we try to follow semantic versioning, the git log does not reflect this changes. We need to configure some hooks/automation for this process.

**Comment by p2kmgcl** [comment]
Some ideas:
- Force fixing security issues (`npm audit fix`) before publishing new versions
- Follow some commit message pattern (probably https://github.com/liferay/liferay-frontend-guidelines/blob/master/general/commit_messages.md)
- Autoincrease version numbers
- Autoplubish new versions

All of these may be done with husky and travis configurations

@victorg1991

**Comment by p2kmgcl** [comment]
Extra idea:
- Only allow "rebase merge" in github to avoid polluting git log

**Comment by p2kmgcl** [comment]
Another:
- Clean published tarball (currently we are publishing all files)

**Comment by victorg1991** [comment]
Makes sense!
