### ISSUE TITLE
Is Generated Configuration file needed?

### ISSUE THREAD

**Issue by mfreeman-xtivia** [liferay/generator-liferay-fragments#89]
Is the _configuration.json_ file that is generated by default when using the sample data needed?

I see that it is referenced by the fragment.json file but otherwise i cannot find any use for it, and cannot find any documentation anywhere for its use?

Can i just delete it and remove the reference to it from the fragment json?

**Comment by codyhoag** [comment]
Hey @mfreeman-xtivia; that is part of a new feature that we have not officially advertised. It will be part of the upcoming DXP 7.2 SP1 release. You can take a look at the unpublished docs to see how it can be used:
- [Making a Fragment Configurable](https://github.com/sez11a/liferay-docs/blob/72-SP1/en/developer/frameworks/articles/web-experience-management/02-page-fragments/03-making-a-fragment-configurable.markdown)
- [Fragment Configuration Types](https://github.com/sez11a/liferay-docs/blob/72-SP1/en/developer/reference/articles/02-web-experience-management/02-page-fragments/02-fragment-configuration-types.markdown)
- [Collection Format](https://github.com/sez11a/liferay-docs/blob/72-SP1/en/developer/frameworks/articles/web-experience-management/02-page-fragments/05-page-fragments-desktop-tools.markdown#collection-format)

**Comment by mfreeman-xtivia** [comment]
Thanks
So is this different that the kind of configuration i can already do using Liferay Fragment Tags?

**Comment by codyhoag** [comment]
Yes; this is a separate feature.

**Comment by mfreeman-xtivia** [comment]
Cody

So i am really intrigued by this, especially the Javascript use case 
(i.e where I access the configuration from JS and not from 
Freemarker/HTML). Unfortunately i am struggling a little bit to digest 
exactly what that would like based on the referenced doco.

Could you provide a brief example of the configuration JSON file and 
corresponding JS file that would access configuration values set by the 
user?

------ Original Message ------

**Comment by p2kmgcl** [comment]
Hi @mfreeman-xtivia,

The [contributed video component](https://github.com/liferay/liferay-portal/tree/master/modules/apps/fragment/fragment-collection-contributor/fragment-collection-contributor-basic-component/src/main/resources/com/liferay/fragment/collection/contributor/basic/component/dependencies/video) uses some configuration from JS (you will see a `configuration` object in the JS with the configuration values).

As @codyhoag referenced [here](https://github.com/sez11a/liferay-docs/blob/72-SP1/en/developer/frameworks/articles/web-experience-management/02-page-fragments/03-making-a-fragment-configurable.markdown), a `configuration` variable is built and sent to the fragments JS, just as the `fragmentElement` variable.

> So is this different that the kind of configuration i can already do using Liferay Fragment Tags?

Finally, to clarify this, the idea is to reduce the need to create new tags/editables, so you can have some dynamic values in your fragments without writing any Java code.

Did you find this feature confusing/unclear/unuseful? I'm glad you're trying this :smile:

**Comment by mfreeman-xtivia** [comment]
> So is this different that the kind of configuration i can already do using Liferay Fragment Tags?

Well at the moment i cannot test it as i dont have access to any Liferay version that has the fix i dont think

As in looking at the code for the video component, it appears that the JS code references 'configuration' as a global. Does that imply that each fragment JS is run in its own sanddbox? by wrapping it inside a function?

**Comment by p2kmgcl** [comment]
All the JS is wrapped inside an anonymous function to avoid unwanted global variables, but no extra sandbox/frame/environment is generated, we just call it with `fragmentElement` and `configuration` variables available.

This is an ugly copy of the generated code:

```js
(function() {
var fragmentElement = document.querySelector('#fragment-37621-ixvt');
var configuration = {"hideControls":false,"bottomSpacing":"3","loop":false,"width":"","mute":true,"align":"flex-start","autoPlay":false,"url":"","height":""};

// Fragment code...

}());
```

**Comment by p2kmgcl** [comment]
Closing this for now, feel free to reopen/open another issue if you need to :smile:
