### ISSUE TITLE
Thumbnails not added to generated zip

### ISSUE THREAD

**Issue by pynklu** [liferay/generator-liferay-fragments#93]
thumbnails end up as an "unnamed" file (no extension) inside the zip.
Latest version of up-to-date versions of npm/node/yo; latest version of generator. 

![afbeelding](https://user-images.githubusercontent.com/17290441/68191297-8c512a80-ffaf-11e9-9b5e-dca549ccfc98.png)

**Comment by p2kmgcl** [comment]
Fixed :tada: 
https://github.com/liferay/generator-liferay-fragments/pull/94
